# Generated by Django 4.2 on 2024-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(null=True, related_name='cursos', to='main.estudiante'),
        ),
    ]
